version: '2'

services:

    # (Optional) Creates a gem cache data volume
    gems-2.4.1:
      image: busybox
      volumes:
        - /data/db
      command: /bin/true

    web_dev:
      build: 
        context: ./docker-development
      environment:
        - RAILS_ENV=${RAILS_ENV_DEVELOPMENT}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE_DEVELOPMENT}
      volumes:
        - .:/app
      volumes_from:
        - gems-2.4.1
      ports:
        - "5122:22"
        - "8080:80"
      networks:
        - node1

    web_prod:
      build: 
        context: ./docker-production
      environment:
        - RAILS_ENV=${RAILS_ENV_PRODUCTION}
        - SECRET_KEY_BASE=${SECRET_KEY_BASE_PRODUCTION}
      volumes:
        - .:/app
      volumes_from:
        - gems-2.4.1
      ports:
        - "5123:22"
        - "8081:80"
      networks:
        - node2


### Networks Setup ############################################

networks:
  node1:
    driver: "bridge"
  node2:
    driver: "bridge"
